name: Deploy Docker Image

on:
  workflow_run:
    workflows: ['Build Docker Image']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Docker image ID
        uses: actions/download-artifact@v2
        with:
          name: image-id

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            CI=true docker stop ndex-backend || true
            CI=true docker rm ndex-backend || true
            CI=true docker image prune -a
            CI=true docker pull xrli/ndex-backend@$(cat image-id)
            CI=true docker run --name=workfall-rocket-rs -d -p 3001:3001 xrli/ndex-backend@$(cat image-id)
